global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'lonely-chat-backend'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['host.docker.internal:3030']
        labels:
          env: dev
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'localhost:3030'